name: CI
on:
  push:
    paths-ignore:
      - 'examples/**'
      - 'HelpSource/**'
      - 'sounds/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'examples/**'
      - 'HelpSource/**'
      - 'sounds/**'
      - '*.md'
  workflow_dispatch:

jobs:

  version-getter:
    runs-on: ubuntu-22.04
    outputs:
      sc-version: ${{ steps.set-version.outputs.version }}

    steps:
      - name: set version string for artifacts
        id: set-version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            FULL_TAG=${GITHUB_REF#refs/tags/}
            SC_VERSION=${FULL_TAG##Version-}
          else
            SC_VERSION=$GITHUB_SHA
          fi
          echo "version=$SC_VERSION" >> $GITHUB_OUTPUT

  build-wasm:
    needs: [version-getter]
    uses: ./.github/workflows/build_wasm.yml
    with:
      sc-version: ${{ needs.version-getter.outputs.sc-version }}
    secrets: inherit
